---
- name: Instalar pip y aiodns
  hosts: droplets
  become: true
  gather_facts: true

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Instalar pip
      apt:
        name: python3-pip
      when: ansible_os_family == 'Debian'

    - name: Instalar aiodns
      pip:
        name: aiodns
